name: Publish NPM Package

on:
  push:
    tags:
      - 'v*'  # 当推送 v 开头的标签时触发。

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 安装 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org/'

      - name: 安装依赖
        run: npm ci

      - name: 代码检查
        run: npm run lint

      - name: 运行测试
        run: npm run test:run

      - name: 构建项目
        run: npm run build

      - name: 发布到 npm
        run: npm publish --access public
        env:
          # 参考教程：https://www.lihuanyu.com/前端/2025/GitHub-Actions-自动发布-npm-包简易指南/
          # 令牌生成管理地址：https://www.npmjs.com/settings/fsyyft/tokens，一次生成最多使用 90 天。
          # Github 密钥管理地址：https://github.com/fsyyft-ts/npmjs-add/settings/secrets/actions。
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
